@startuml

package 用户域 {
    账户 <|-- 登录账户

    交易员 <|-- 真实交易员
    交易员 <|-- 机器人交易员

    用户 <|-- 交易员
    用户 o-- 登录账户
}

package 交易域 {

  账户 <|-- 交易账户
  交易员 o-- 交易账户

  交易账户 *-- 交易钱包
  交易账户 *-- 交易凭证处理器

  交易凭证 <-- 交易凭证处理器
  交易凭证 <-- 行情
  交易凭证 <-- 成交单处理器

  交易标的 *-- 行情
  交易标的 *-- 交易凭证
  交易标的 *-- 撮合引擎

  交易凭证 *-- 成交单处理器
  交易凭证 *-- 委托单发送器
  交易凭证 *-- 委托单处理器

  委托单处理器 *-- 委托账本

  委托单 <-- 交易账户
  委托单 <-- 委托单发送器
  委托单 <-- 委托单处理器
  委托单 <-- 委托账本

}

@enduml
